version: '3'

services:
  app:
    profiles: ['devcontainer']
    container_name: skku-ejs-dev
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:18-bullseye
    volumes:
      - .:/workspace:cached
    stdin_open: true
    tty: true
    environment:
      DEVCONTAINER: 1
  dev-db:
    container_name: skku-ejs-dev-db
    image: postgres:14-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: skku
  gitolite:
    container_name: gitolite-server
    image: elsdoerfer/gitolite
    ports:
      - 22:22
    environment:
      SSH_KEY: ${SSH_KEY}
    