version: '3'

services:
  app:
    profiles: ['devcontainer']
    container_name: skku-ejs-dev
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:18-bullseye
    ports:
      - 4000:4000
    volumes:
      - .:/workspace:cached
    stdin_open: true
    tty: true
    environment:
      DEVCONTAINER: 1
  dev-db:
    container_name: skku-ejs-dev-db
    image: postgres:14-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: skku
  minio: 
    container_name: skku-ejs-dev-minio
    image: quay.io/minio/minio:RELEASE.2023-08-09T23-30-22Z
    command: server /workspace/minio --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - .:/workspace:cached