version: '3'

services:
  server:
    container_name: ejp-be
    build:
      dockerfile: ./builder/Dockerfile
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    container_name: ejp-db
    image: postgres:14-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: skku
  minio:
    container_name: ejp-minio
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: skku-ejs
      MINIO_ROOT_PASSWORD: 12345678

  mcservice:
    container_name: ejp-minio-mc
    image: minio/mc
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://EJP-minio:9000 skku-ejs 12345678;
      /usr/bin/mc mb myminio/test;
      /usr/bin/mc policy set public myminio/test;
      "